{% set name = "scikits_odes_sundials" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 277d0400812f63a11624565d82f9ecc7497263ebfb9f049e5ca8ab2d025c5621

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython <3
    - libblas
    - numpy
    - setuptools
    - sundials >=6,<7
  run:
    - python
    - sundials >=6,<7

test:
  imports:
    - numpy
    - scikits_odes_sundials
  files:
    - integrate.py
  commands:
    - python integrate.py

about:
  home: https://github.com/bmcage/odes
  summary: Sundials wrapper module for scikits.odes
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Odes is a scikit toolkit for scipy to add extra ode solvers. Specifically
    it interfaces the SUNDIALS solvers (i.e., cvode, cvodes, ida, and idas),
    providing extra ODE and DAE solvers you can use, beyond those already in
    scipy.integrate.ode.
  doc_url: https://scikits-odes.readthedocs.io
  dev_url: https://github.com/bmcage/odes

extra:
  recipe-maintainers:
    - c-randall
